#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Terminal Hue', '0.1.0');
$app->add(new TerminalHue\Commands\Setup);
$app->add(new TerminalHue\Commands\Light);
$app->add(new TerminalHue\Commands\Lights);

$app->run();